### ISSUE TITLE
Tests are hanging with v4.0.0

### ISSUE THREAD

**Issue by joeypedicini92** [ember-cli/ember-cli-qunit#182]
After updating to ember-cli-qunit 4.0.0, when running tests either with `ember test` or `ember test --server` the tests just hang infinitely until you quit the process.

ember v2.12 and v2.13
node v6.9.1

**Comment by trentmwillis** [comment]
Did you follow the upgrading instructions and invoke `start()` in your `test-helper.js` file? [Ref](https://github.com/ember-cli/ember-cli-qunit#upgrading).

**Comment by joeypedicini92** [comment]
my bad. definitely forgot to read the readme until about a minute after posting this. you can close this issue.

**Comment by trentmwillis** [comment]
No worries, let us know if any other issues are run into!

**Comment by ultimatemonty** [comment]
@trentmwillis I'm seeing something similar when updating to 4.0.0. Tests hang in terminal and have to kill the process. Every test in the browser instance fails with the following:

```
Died on test #1     at QUnit.test.global.test (http://localhost:7357/assets/test-support.js:12032:16)
    at Module.callback (http://localhost:7357/assets/tests.js:37005:23)
    at Module.exports (http://localhost:7357/assets/vendor.js:119:32)
    at requireModule (http://localhost:7357/assets/vendor.js:34:18)
    at TestLoader.require (http://localhost:7357/assets/test-support.js:12321:7)
    at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:12313:14)
    at loadTests (http://localhost:7357/assets/test-support.js:12185:22): Cannot read property 'call' of null@ 34 ms
Expected: 	
null
Message: 	Diff suppressed as the expected and actual results have an equivalent serialization
Source: 	
TypeError: Cannot read property 'call' of null
    at runTest (http://localhost:7357/assets/test-support.js:3294:29)
    at Test.run (http://localhost:7357/assets/test-support.js:3280:6)
    at http://localhost:7357/assets/test-support.js:3472:12
    at Object.advance (http://localhost:7357/assets/test-support.js:2957:26)
    at begin (http://localhost:7357/assets/test-support.js:4648:20)
    at http://localhost:7357/assets/test-support.js:3842:6
```

here's my package.json and test-support.js:
```
// package.json
{
  "name": "my-app",
  "version": "",
  "description": "A wonderful application",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test",
    "lint": "ember test --filter 'ESLint'"
  },
  "repository": "",
  "engines": {
    "node": ">= 4"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "broccoli-funnel": "0.2.15",
    "ember-ajax": "^3.0.0",
    "ember-cli": "2.13.0",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-bootstrap-datepicker": "0.5.5",
    "ember-cli-bootstrap-datetimepicker": "0.4.1",
    "ember-cli-code-coverage": "ming-codes/ember-cli-code-coverage#bugfix/hang-0.3.9",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-deploy": "^1.0.0",
    "ember-cli-deploy-build": "^1.0.0",
    "ember-cli-deploy-json-config": "^1.0.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-mirage": "0.1.13",
    "ember-cli-moment-shim": "3.0.1",
    "ember-cli-page-object": "1.6.0",
    "ember-cli-pretender": "0.4.0",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "5.3.0",
    "ember-cli-sauce": "1.4.4",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-concurrency": "0.7.8",
    "ember-data": "2.10.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-lodash": "0.0.6",
    "ember-modal-dialog": "0.9.0",
    "ember-power-select": "1.0.0-beta.22",
    "ember-radio-button": "1.0.7",
    "ember-resolver": "^4.0.0",
    "ember-route-action-helper": "0.3.1",
    "ember-source": "~2.13.0",
    "ember-test-helpers": "^0.5.22",
    "ember-truth-helpers": "1.1.0",
    "emberx-select": "2.0.1",
    "eonasdan-bootstrap-datetimepicker-npm": "4.17.42",
    "loader.js": "^4.2.3",
    "moment": "2.17.1",
    "moment-timezone": "0.5.11"
  },
  "dependencies": {}
}
```

```
// tests/test-support.js
import resolver from './helpers/resolver';
import { setResolver } from 'ember-qunit';
import { start } from 'ember-cli-qunit';

setResolver(resolver);
start();
```

**Comment by ultimatemonty** [comment]
@trentmwillis ahh crap just saw you closed this as I was reviewing my comment - would you like me to open a new issue?

**Comment by trentmwillis** [comment]
Would be better to open a new issue. Also, can you include what version you are upgrading from?

**Comment by rwjblue** [comment]
And ideally a way to reproduce the issue...
