### ISSUE TITLE
Tests hanging upgrading from 2.2.5 to 4.0.0

### ISSUE THREAD

**Issue by ultimatemonty** [ember-cli/ember-cli-qunit#183]
I'm seeing an issue when updating to 4.0.0. Tests are hanging in terminal and I have to kill the process instead of using `q` or `ctrl-c`.

Every test in the browser instance fails with the following:

```
Died on test #1     at QUnit.test.global.test (http://localhost:7357/assets/test-support.js:12032:16)
    at Module.callback (http://localhost:7357/assets/tests.js:37005:23)
    at Module.exports (http://localhost:7357/assets/vendor.js:119:32)
    at requireModule (http://localhost:7357/assets/vendor.js:34:18)
    at TestLoader.require (http://localhost:7357/assets/test-support.js:12321:7)
    at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:12313:14)
    at loadTests (http://localhost:7357/assets/test-support.js:12185:22): Cannot read property 'call' of null@ 34 ms
Expected: 	
null
Message: 	Diff suppressed as the expected and actual results have an equivalent serialization
Source: 	
TypeError: Cannot read property 'call' of null
    at runTest (http://localhost:7357/assets/test-support.js:3294:29)
    at Test.run (http://localhost:7357/assets/test-support.js:3280:6)
    at http://localhost:7357/assets/test-support.js:3472:12
    at Object.advance (http://localhost:7357/assets/test-support.js:2957:26)
    at begin (http://localhost:7357/assets/test-support.js:4648:20)
    at http://localhost:7357/assets/test-support.js:3842:6
```

here's my package.json and test-support.js:
```
// package.json
{
  "name": "my-app",
  "version": "",
  "description": "A wonderful application",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test",
    "lint": "ember test --filter 'ESLint'"
  },
  "repository": "",
  "engines": {
    "node": ">= 4"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "broccoli-funnel": "0.2.15",
    "ember-ajax": "^3.0.0",
    "ember-cli": "2.13.0",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-bootstrap-datepicker": "0.5.5",
    "ember-cli-bootstrap-datetimepicker": "0.4.1",
    "ember-cli-code-coverage": "ming-codes/ember-cli-code-coverage#bugfix/hang-0.3.9",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-deploy": "^1.0.0",
    "ember-cli-deploy-build": "^1.0.0",
    "ember-cli-deploy-json-config": "^1.0.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-mirage": "0.1.13",
    "ember-cli-moment-shim": "3.0.1",
    "ember-cli-page-object": "1.6.0",
    "ember-cli-pretender": "0.4.0",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "5.3.0",
    "ember-cli-sauce": "1.4.4",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-concurrency": "0.7.8",
    "ember-data": "2.10.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-lodash": "0.0.6",
    "ember-modal-dialog": "0.9.0",
    "ember-power-select": "1.0.0-beta.22",
    "ember-radio-button": "1.0.7",
    "ember-resolver": "^4.0.0",
    "ember-route-action-helper": "0.3.1",
    "ember-source": "~2.13.0",
    "ember-test-helpers": "^0.5.22",
    "ember-truth-helpers": "1.1.0",
    "emberx-select": "2.0.1",
    "eonasdan-bootstrap-datetimepicker-npm": "4.17.42",
    "loader.js": "^4.2.3",
    "moment": "2.17.1",
    "moment-timezone": "0.5.11"
  },
  "dependencies": {}
}
```

```
// tests/test-support.js
import resolver from './helpers/resolver';
import { setResolver } from 'ember-qunit';
import { start } from 'ember-cli-qunit';

setResolver(resolver);
start();
```

**Comment by ultimatemonty** [comment]
additionally we have had issues upgrading past 2.x for some time. Was hoping 4.0.0 would resolve those issues. Let me go back and reproduce those issues and I can post some additional details.

**Comment by rwjblue** [comment]
>    `at loadTests (http://localhost:7357/assets/test-support.js:12185:22): Cannot read property 'call' of null@ 34 ms`

What is in `dist/assets/test-support.js` at line 12185?

**Comment by ultimatemonty** [comment]
@rwjblue looks sinon related. I think maybe our version of sinon and sinon-qunit are out of date? Installing `ember-sinon-qunit` latest and will report back.

![image](https://cloud.githubusercontent.com/assets/7738688/25681209/7ec7e1ca-3021-11e7-9bae-8e5d15c97800.png)

**Comment by trentmwillis** [comment]
If you've had issues upgrading past 2.x of ember-cli-qunit, then that likely means you have code that isn't compatible with QUnit 2.x. I would recommend checking out the migration guide here: http://qunitjs.com/upgrade-guide-2.x/

**Comment by ultimatemonty** [comment]
@trentmwillis awesome thanks for the link - had not seen that when bumping versions in our earlier upgrades. Will close this issue and work through that guide.

**Comment by jamesarosen** [comment]
I'm seeing the same thing in my app.

With ember-cli-qunit@3.1.2, the tests run fine. There are no deprecation warnings or failures.

With ember-cli-qunit@4.0.0, the test page shows up with an empty iframe. There's no test harness UI. There are no errors in the console.

I'm happy to provide more information, but I'm not sure what would be useful. My dependencies resolve to testem@1.16.1, ember-qunit@2.1.3, qunitjs@2.3.2.

**Comment by trentmwillis** [comment]
@jamesarosen did you invoke the new `start()` function?

**Comment by jamesarosen** [comment]
> did you invoke the new `start()` function?

Sure didn't! I didn't see https://github.com/ember-cli/ember-cli-qunit#upgrading, though it's pretty clear.
