### ISSUE TITLE
Error: Merge error: conflicting capitalizations

### ISSUE THREAD

**Issue by luketheobscure** [ember-cli/ember-cli-qunit#195]
I'm opening this issue mostly so that anyone with the same issue will be able to find the solution. With ember-cli-qunit v4.0.1 we started getting this on our CI servers:

```
[21:18:19]	[Step 8/9] Error: Merge error: conflicting capitalizations:
[21:18:19]	[Step 8/9] README.md in /home/teamcity/BuildAgent/work/e67c00139f3f910f/tmp/broccoli_merge_trees-input_base_path-3w79qP7I.tmp/2
[21:18:19]	[Step 8/9] readme.md in /home/teamcity/BuildAgent/work/e67c00139f3f910f/tmp/broccoli_merge_trees-input_base_path-3w79qP7I.tmp/2
[21:18:19]	[Step 8/9] Remove one of the files and re-add it with matching capitalization.
```

I'm still not sure the exact cause of the issue (never able to reproduce locally... seems like a linux only issue), but updating to v4.0.2 fixed the issue.

**Comment by rwjblue** [comment]
Wild! I'm sorry you had issues, I'm not quite sure where the issue was coming from but I'm glad you got it working...

**Comment by chendraayan** [comment]
We ran into the same error recently. We are using ember-cli-qunit v4.4.0. And we have not changed ember-svg-jar version recently. We have not found the solution yet.
```
Merge error: conflicting capitalizations:
ember-svg-jar/inlined/Loader.js in /tmp/broccoli-18FQIzjvy9zz8U/out-1308-broccoli_persistent_filter_babel_babel_ember_svg_jar_ba
ember-svg-jar/inlined/loader.js in /tmp/broccoli-18FQIzjvy9zz8U/out-1381-broccoli_merge_trees_addon_tree_for_common_addon
Remove one of the files and re-add it with matching capitalization.
    at MergeTrees._getMergedDirectory2 (/test/node_modules/broccoli-merge-trees/node_modules/merge-trees/index.js:96:19)
    at MergeTrees._getMergedDirectory2 (/test/node_modules/broccoli-merge-trees/node_modules/merge-trees/index.js:174:33)
    at MergeTrees._getMergedDirectory2 (/test/node_modules/broccoli-merge-trees/node_modules/merge-trees/index.js:174:33)
    at MergeTrees._getMergedDirectory (/test/node_modules/broccoli-merge-trees/node_modules/merge-trees/index.js:40:17)
    at MergeTrees.merge (/test/node_modules/broccoli-merge-trees/node_modules/merge-trees/index.js:27:20)
    at BroccoliMergeTrees.build (/test/node_modules/broccoli-merge-trees/index.js:36:21)
    at /test/node_modules/broccoli/lib/wrappers/transform-node.js:29:35
    at new Promise (<anonymous>)
    at TransformNodeWrapper.build (/test/node_modules/broccoli/lib/wrappers/transform-node.js:21:12)
    at /test/node_modules/broccoli/lib/builder.js:116:28
```
