### ISSUE TITLE
Path or pattern "passed.png" did not match any files

### ISSUE THREAD

**Issue by ilkkao** [ember-cli/ember-cli-qunit#31]
Just upgraded to ember-cli v0.10.0 and saw this error after `ember build` I tried to follow the instructions and deleted all generated and temp files. 

Could this be related to https://github.com/ember-cli/ember-cli-qunit/pull/30?

```
Path or pattern "passed.png" did not match any files
Error: Path or pattern "passed.png" did not match any files
    at Object.multiGlob (/Users/ilkkao/git/mas/client/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at /Users/ilkkao/git/mas/client/node_modules/ember-cli/node_modules/broccoli-static-compiler/index.js:28:27
    at $$$internal$$tryCatch (/Users/ilkkao/git/mas/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/ilkkao/git/mas/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/ilkkao/git/mas/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:473:11)
    at $$rsvp$asap$$flush (/Users/ilkkao/git/mas/client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1581:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by ilkkao** [comment]
Wrong link. I mean https://github.com/ember-cli/ember-cli-qunit/pull/30

**Comment by ilkkao** [comment]
Stupid me. `ember-qunit-*` packages got lost from my bower.json during the upgrade.
