### ISSUE TITLE
ember g ember-cli-qunit fails on ember-cli-test-loader

### ISSUE THREAD

**Issue by blimmer** [ember-cli/ember-cli-qunit#72]
```
› ember g ember-cli-qunit
version: 1.13.6
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
installing ember-cli-qunit
Installing browser packages via Bower...
  not-cached git://github.com/rwjblue/ember-qunit-builds.git#0.4.6
  cached git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
  cached git://github.com/jquery/qunit.git#1.17.1
  resolved git://github.com/rwjblue/ember-qunit-builds.git#0.4.6
Package ember-cli/ember-cli-test-loader=ember-cli/ember-cli-test-loader not found
Error: Package ember-cli/ember-cli-test-loader=ember-cli/ember-cli-test-loader not found
    at createError (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
    at _fulfilled (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:796:13)
    at /Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

**Comment by blimmer** [comment]
This same thing happens on ember-cli-mocha, too, as [reported here](https://github.com/switchfly/ember-cli-mocha/issues/68)

**Comment by stefanpenner** [comment]
may be related to: https://github.com/ember-cli/ember-cli/pull/4430

**Comment by blimmer** [comment]
Yep, I just fixed it in ember-cli-mocha, PR coming here soon.

**Comment by stefanpenner** [comment]
@blimmer im not sure that is the right fix, this is surprising behavior, the original should continue to work I believe. Or do you feel it shouldn't ?

**Comment by blimmer** [comment]
It definitely does not work as it stands. Try to `ember new` a new project on ember-cli 1.13.7 and run `ember g ember-cli-qunit`.

```
› ember g ember-cli-qunit
version: 1.13.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
installing ember-cli-qunit
Installing browser packages via Bower...
  cached git://github.com/jquery/qunit.git#1.18.0
  cached git://github.com/rwjblue/ember-qunit-builds.git#0.4.9
  cached git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
Package ember-cli/ember-cli-test-loader=ember-cli/ember-cli-test-loader not found
Error: Package ember-cli/ember-cli-test-loader=ember-cli/ember-cli-test-loader not found
    at createError (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
    at _fulfilled (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:796:13)
    at /Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/Users/blimmer/code/oss/ember-cli-example-app-for-github/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

Changing `node_modules/ember-cli-qunit/blueprints/ember-cli-qunit/index.js` to include source (as I've done in this PR) fixes that error.

**Comment by stefanpenner** [comment]
yes but my argument is before this worked without source, i suspect the fix is restoring that functionality. Or discovering why it can not be.

**Comment by blimmer** [comment]
I agree that the old way should still work. Perhaps the fix should be in cli.

**Comment by stefanpenner** [comment]
> Perhaps the fix should be in cli.

Ya, im just about to investigate what is going on. I would prefer to fix it at the source (no pun intended)
